Repository Yelp/Tron, pull requests merged in 2018-04, with the labels that each got.

#409 add a script to clean up namespace
  contrib/namespace_cleanup.sh
Labels: in review

#404 fix the action_status command
  bin/action_runner.py
  bin/action_status.py
  tests/bin/action_status_test.py
Labels: in review

#406 Try to fix doc building
  .pre-commit-config.yaml
  docs/conf.py
Labels: in review

#410 Fix timestamp with timezone and remove flaky test
  tests/utils/timeutils_test.py
  tron/utils/timeutils.py
Labels: in review

#414 Don't delete file if namespace is incorrect
  tests/config/manager_test.py
  tron/config/manager.py
Labels: in review

#416 service code clean up
  contrib/find_forgotten_procs.py
  docs/command_context.rst
  docs/conf.py
  docs/config.rst
  docs/index.rst
  docs/man_tronctl.rst
  docs/man_trond.rst
  docs/man_tronview.rst
  docs/overview.rst
  docs/sample_config.yaml
  docs/services.rst
  docs/tutorial.rst
  tools/migration/migrate_state.py
  tron/serialize/runstate/__init__.py
  tronweb_tests/SpecRunner.html
Labels: in review

#407 Added the action_runner for localhost on the example_cluster
  example-cluster/config/MASTER.yaml
  example-cluster/docker-compose.yml
  example-cluster/images/batch/Dockerfile
  example-cluster/start.sh
  example-cluster/tronfig/MASTER.yaml
Labels: in review

#401 First Stab at Action retries
  tests/config/config_parse_test.py
  tests/core/actionrun_test.py
  tron/api/controller.py
  tron/config/config_parse.py
  tron/config/schema.py
  tron/config/tronfig_schema.json
  tron/core/action.py
  tron/core/actionrun.py
  tron/utils/state.py
Labels: in review

#417 Disconnect state version from release version
  tron/serialize/runstate/statemanager.py
Labels: in review

#419 Fix namespace with non-ascii crashing tronfig
  bin/tronfig
  tron/config/manager.py
Labels: in review

#421 monitoring alert if any action becomes failed or unknown
  bin/check_tron_jobs.py
  tests/bin/check_tron_jobs_test.py
Labels: in review

#422 Deal with requestargs encoding in get_string()
  tests/api/requestargs_test.py
  tests/api/resource_test.py
  tron/api/requestargs.py
  tron/api/resource.py
Labels: in review

#420 set a smart realert_every
  bin/check_tron_jobs.py
  tests/bin/check_tron_jobs_test.py
Labels: in review

#424 Fix validation of cleanup action
  example-cluster/config/MASTER.yaml
  tron/config/config_parse.py
  tron/config/schema.py
Labels: in review

#415 Run the example_cluster under faketime 10x faster than real life
  example-cluster/start.sh
  example-cluster/tronfig/MASTER.yaml
  yelp_package/trusty/Dockerfile
Labels: in review

#426 Maybe decode all the things
  .gitignore
  bin/tronrepl
  dev/req_dev.txt
  example-cluster/config/MASTER.yaml
  example-cluster/start.sh
  setup.py
  tron/api/resource.py
  tron/core/action.py
  tron/core/actiongraph.py
  tron/core/actionrun.py
  tron/core/job.py
  tron/core/jobrun.py
  tron/serialize/runstate/shelvestore.py
  tron/utils/__init__.py
Labels: in progress

#427 speed up tronview command with zero args
  bin/tronview
  tests/api/resource_test.py
  tests/commands/client_test.py
  tron/api/adapter.py
  tron/api/resource.py
  tron/commands/client.py
Labels: in review

#428 Always send signals to the full process group in the tron action runner
  .gitignore
  bin/action_status.py
  tests/bin/action_status_test.py
Labels: in review

#370 Python3 deb
  .gitignore
  .travis.yml
  Makefile
  bin/tronctl
  bin/trond
  bin/tronrepl
  debian/changelog
  debian/control
  debian/rules
  example-cluster/docker-compose.yml
  example-cluster/images/trusty
  example-cluster/images/xenial
  example-cluster/start.sh
  itest.sh
  tests/api/resource_test.py
  tests/commands/client_test.py
  tox.ini
  tron/__init__.py
  tron/actioncommand.py
  tron/api/adapter.py
  tron/api/resource.py
  tron/commands/client.py
  tron/commands/display.py
  tron/core/actionrun.py
  tron/node.py
  tron/serialize/runstate/statemanager.py
  tron/utils/state.py
  yelp_package/trusty/Dockerfile
  yelp_package/xenial/Dockerfile
Labels: in progress

#432 Fix Xenial build
  yelp_package/xenial/Dockerfile
Labels: in review

#418 Add retry action
  bin/tronctl
  debian/changelog
  tests/core/actionrun_test.py
  tox.ini
  tron/__init__.py
  tron/api/controller.py
  tron/core/actionrun.py
  tronweb/coffee/actionrun.coffee
Labels: in review

#435 maybe_encode all data in the file serializer
  tron/actioncommand.py
  tron/serialize/filehandler.py
Labels: in review

#436 Added retry docs
  CHANGELOG.md
  docs/jobs.rst
  docs/man_tronctl.rst
  docs/whats-new.rst
Labels: in review

#387 Remove tron/utils/collections
  .gitignore
  CHANGELOG.md
  Makefile
  bin/action_runner.py
  bin/tronctl
  debian/changelog
  dev/req_dev.txt
  dev/req_docs.txt
  docs/jobs.rst
  docs/man_tronctl.rst
  docs/whats-new.rst
  example-cluster/config/MASTER.yaml
  example-cluster/config/_manifest.yaml
  example-cluster/docker-compose.yml
  example-cluster/images/batch/Dockerfile
  example-cluster/start.sh
  example-cluster/tronfig/MASTER.yaml
  example-cluster/tronfig/_manifest.yaml
  itest.sh
  tests/api/resource_test.py
  tests/config/config_parse_test.py
  tests/config/config_utils_test.py
  tests/config/schedule_parse_test.py
  tests/core/action_test.py
  tests/core/actiongraph_test.py
  tests/core/actionrun_test.py
  tests/core/job_test.py
  tests/node_test.py
  tests/scheduler_test.py
  tests/utils/collections_test.py
  tox.ini
  tron/__init__.py
  tron/actioncommand.py
  tron/api/controller.py
  tron/api/requestargs.py
  tron/api/resource.py
  tron/config/config_parse.py
  tron/config/config_utils.py
  tron/config/manager.py
  tron/config/schedule_parse.py
  tron/config/schema.py
  tron/core/action.py
  tron/core/actionrun.py
  tron/core/job.py
  tron/node.py
  tron/serialize/filehandler.py
  tron/serialize/runstate/statemanager.py
  tron/utils/collections.py
  tronweb/coffee/actionrun.coffee
  yelp_package/trusty/Dockerfile
  yelp_package/xenial/Dockerfile
Labels: in review

#437 Pre calculate state machine transitions
  tron/utils/state.py
Labels: api, in review, performance
